# Generated by Django 3.1.4 on 2020-12-26 06:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código de la categoría')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la categoría')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Texto descriptivo de la categoría')),
                ('activo', models.CharField(choices=[('Si', 'Activo'), ('No', 'Inactivo')], default='Si', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('tipo_doc', models.CharField(choices=[('Cc', 'Cédula'), ('Pa', 'Pasaporte'), ('Ce', 'Cédula de extranjería')], default='Cc', max_length=2, verbose_name='Tipo Doc. Identidad')),
                ('doc_identificacion', models.CharField(max_length=15, verbose_name='Documento identificación')),
                ('dir_env', models.CharField(max_length=100, verbose_name='Dirección de envío')),
                ('fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('activo', models.CharField(choices=[('Si', 'Activo'), ('No', 'Inactivo')], default='Si', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(default=datetime.date.today, verbose_name='Fecha del pedido')),
                ('forma_pago', models.CharField(choices=[('PSE', 'PSE'), ('Tj', 'Tarjeta de crédito'), ('Py', 'Paypal'), ('Mp', 'Mercado pago')], default='PSE', max_length=3, verbose_name='Forma de pago')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor total')),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(choices=[('Rg', 'Registrado'), ('Pr', 'Preparación'), ('En', 'Enviado'), ('Re', 'Recibido cliente'), ('Fn', 'Finalizado sin reclamaciones'), ('Fr', 'Finalizado con reclamaciones'), ('Ca', 'Cancelado')], default='Rg', max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendavirtualapp.clientes')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código del producto')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Texto descriptivo del producto')),
                ('unidad', models.CharField(choices=[('Kg', 'Kilogramo'), ('Lb', 'Libra'), ('Un', 'Unidad'), ('Pa', 'Paquete')], default='Kg', max_length=2)),
                ('fecha_registro', models.DateField(default=datetime.date.today, verbose_name='Fecha de registro')),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_precio', models.DateField(default=datetime.date.today, verbose_name='Fecha de modificación')),
                ('activo', models.CharField(choices=[('Si', 'Activo'), ('No', 'Inactivo')], default='Si', max_length=2)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.categorias')),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductosPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.pedidos')),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(choices=[('CeB', 'Bogeda Centro Cr 3b 12-23 Bog'), ('SuB', 'Bogeda Sur Calle 34c 14-13 Bog'), ('NoB', 'Bogeda Norte Calle 3b 64-23 Bog')], default='NoB', max_length=3)),
                ('precio_entrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tiendavirtualapp.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Calificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.CharField(choices=[('1', '[1] estrella'), ('2', '[2] estrellas'), ('3', '[3] estrellas'), ('4', '[4] estrellas'), ('5', '[5] estrellas')], default='5', max_length=1)),
                ('fecha_calificacion', models.DateField(default=datetime.date.today)),
                ('comentario', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendavirtualapp.clientes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendavirtualapp.productos')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
    ]
