# Generated by Django 3.1.4 on 2020-12-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtualapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productospedido',
            old_name='productos',
            new_name='producto',
        ),
    ]
