# Generated by Django 3.1.4 on 2020-12-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtualapp', '0002_auto_20201226_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='descripcion',
            field=models.TextField(verbose_name='Texto descriptivo de la categoría'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(verbose_name='Texto descriptivo del producto'),
        ),
    ]
