# Generated by Django 3.1.4 on 2020-12-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtualapp', '0003_auto_20201226_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
